name: MealPlan
version: "1.0.0-4f38826-3d5d39b-c075e9f"
slug: mealplan
description: Mobile-first meal planning application with drag-and-drop organization
url: "https://github.com/jhaals/mealplan"
image: "ghcr.io/jhaals/mealplan-{arch}"
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: services
boot: auto
ports:
  3001/tcp: 3001
ports_description:
  3001/tcp: Web interface
options:
  port: 3001
schema:
  port: "port?"
