name: MealPlan
version: "1.0.0-4f38826-3d5d39b-c075e9f-5bee58b-b72ba3e-af11488-cc808c9-06df020-3887dbe-7222e96-dc6a4df"
slug: mealplan
description: Mobile-first meal planning application with drag-and-drop organization
url: "https://github.com/jhaals/mealplan"
image: "ghcr.io/jhaals/mealplan-{arch}"
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: services
boot: auto
ports:
  3001/tcp: 3001
ports_description:
  3001/tcp: Web interface
options:
  port: 3001
  trmnl_webhook_url: ""
  google_api_key: ""
  language: "en"
schema:
  port: "port?"
  trmnl_webhook_url: "str?"
  google_api_key: "str?"
  language: "list(en|sv)?"
